# Generated by Django 3.1.3 on 2020-11-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantSlug', models.SlugField(default='xyz', primary_key=True, serialize=False)),
                ('resName', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(null=True)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('first', models.CharField(blank=True, max_length=10)),
                ('second', models.CharField(blank=True, max_length=10)),
                ('third', models.CharField(blank=True, max_length=10)),
                ('fourth', models.CharField(blank=True, max_length=10)),
                ('fifth', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(blank=True, max_length=10)),
                ('duration', models.DurationField(null=True)),
                ('cost', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
