<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-23 12:35
=======
# Generated by Django 3.1.3 on 2020-11-21 18:50
>>>>>>> 994b4b060b99b6a0ad05de867ab28fb03fd8b59e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
<<<<<<< HEAD
                ('restaurantSlug', models.SlugField(default='xyz', primary_key=True, serialize=False)),
                ('resName', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(null=True)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('first', models.CharField(blank=True, max_length=10)),
                ('second', models.CharField(blank=True, max_length=10)),
                ('third', models.CharField(blank=True, max_length=10)),
                ('fourth', models.CharField(blank=True, max_length=10)),
                ('fifth', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(blank=True, max_length=10)),
                ('duration', models.DurationField(null=True)),
                ('cost', models.CharField(blank=True, max_length=10)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_num', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(blank=True, max_length=10)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('first', models.CharField(blank=True, max_length=6)),
                ('second', models.CharField(blank=True, max_length=6)),
                ('third', models.CharField(blank=True, max_length=6)),
                ('fourth', models.CharField(blank=True, max_length=6)),
                ('fifth', models.CharField(blank=True, max_length=6)),
                ('duration', models.DurationField()),
                ('cost', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
>>>>>>> 994b4b060b99b6a0ad05de867ab28fb03fd8b59e
            ],
        ),
    ]
