# Generated by Django 3.1.3 on 2020-11-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishtype', models.CharField(blank=True, max_length=200)),
                ('dishname', models.CharField(blank=True, max_length=200)),
                ('dishdetails', models.CharField(blank=True, max_length=500)),
                ('cuisine', models.CharField(blank=True, max_length=200)),
                ('dishpic', models.ImageField(blank=True, max_length=200, upload_to='')),
                ('price', models.CharField(blank=True, max_length=10)),
                ('buzzwords', models.CharField(blank=True, max_length=1000)),
                ('restaurantSlug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.restaurant')),
            ],
        ),
    ]
