# Generated by Django 3.1.3 on 2020-11-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
