# Generated by Django 3.1.3 on 2020-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201123_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='buzzwords',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishdetails',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
