# Generated by Django 3.1.3 on 2020-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201123_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='extraWords',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
