# Generated by Django 3.1.3 on 2020-11-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20201126_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantImage',
            field=models.ImageField(blank=True, null=True, upload_to='resimage'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantLogo',
            field=models.ImageField(blank=True, null=True, upload_to='reslogo'),
        ),
    ]
